ATTRIBUTES = {"Animal Friendship":1,
              "Appearance":1,
              "Art of Distraction":1,
              "Astral Projection":3,
              "Aura of Command":1,
              "Combat Mastery":2,
              "Contamination [Hard]":1,
              "Contamination [Easy]":2,
              "Damn Healthy!":1,
              "Dimensional Portal [Fixed]":2,
              "Dimensional Portal [Mobile]":3,
              "Dimensional Portal [Class]":4,
              "Divine Relationship":1,
              "Dynamic Sorcery":4,
              "Elasticity":1,
              "ECM":1,
              "Energy Bonus":1,
              "Environmental Control [1]":1,
              "Environmental Control [2]":2,
              "Exorcism":1,
              "Extra Arms":1,
              "Extra Attacks":4,
              "Features/Accessories":1,
              "Flight [Airplane]":3,
              "Flight [Hover]":4,
              "Flunkies":1,
              "Focused Damage":1,
              "Force Field [Wall]":2,
              "Force Field [Personal]":3,
              "Force Field [Extendable]":4,
              "Ground Speed":2,
              "Gun Bunny":1,
              "Healing":4,
              "Heavy Armour":4,
              "Heightened Awareness":1,
              "Heightened Senses":1,
              "Highly Skilled":1,
              "Illusion [One Sense]":2,
              "Illusion [Two Senses]":3,
              "Illusion [Three Senses]":4,
              "Illusion [Four Senses]":5,
              "Illusion [All Senses]":6,
              "Insubstantial":4,
              "Invisibility [Normal]":5,
              "Invisibility [Sensors]":3,
              "Invisibility [Both]":7,
              "Item of Power":2,
              "Jumping":1,
              "Kensei":1,
              "Life Support":1,
              "Light Armour":1,
              "Magic":4,
              "Massive Damage":2,
              "Mechanical Genius":2,
              "Meld [Inanimate Class]":2,
              "Meld [Inanimate]":4,
              "Meld [Animate Class]":4,
              "Meld [Animate]":8,
              "Metamorphosis":5,
              "Mind Control [Single Type]":1,
              "Mind Control [Specific]":2,
              "Mind Control [Broad]":3,
              "Mind Control [General]":4,
              "Mind Shield":1,
              "Natural Weapons":1,
              "Organizational Ties [Moderate]":1,
              "Organizational Ties [Significant]":2,
              "Organizational Ties [Great]":3,
              "Own a Big Mecha":4,
              "Personal Gear":1,
              "Place of Power":1,
              "Precognition [Uncontrolled]":1,
              "Precognition [Controllable]":2,
              "Regeneration":4,
              "Reincarnation":3,
              "Sensors":1,
              "Servant [Specific]":1,
              "Servant [Replaceable]":2,
              "Shape Change [Self or Others]":2,
              "Shape Change [Self and Others]":3,
              "Shield":1,
              "Sixth Sense":1,
              "Size Change [Shrink or Grow]":1,
              "Size Change [Shrink and Grow]":2,
              "Space Flight":2,
              "Special Defense":1,
              "Special Movement":1,
              "Speed":1,
              "Spirit Ward":1,
              "Star Flight":2,
              "Stealth":1,
              "Super Strength [Single Limb]":2,
              "Super Strength [Entire Body]":3,
              "Swarm":2,
              "Telekinesis [Focused]":1,
              "Telekinesis [General]":2,
              "Telepathy [Quite Restricted]":1,
              "Telepathy [Somewhat Restricted]":2,
              "Telepathy [Universal]":3,
              "Teleport [Self or Others]":5,
              "Teleport [Self and Others]":10,
              "Transmutation [Very Specific]":1,
              "Transmutation [Class]":2,
              "Transmutation [Universal]":4,
              "Tunnelling":2,
              "Water Speed [Surface]":2,
              "Water Speed [Amphibious/Diving]":3,
              "Weapon/Special Attack":4}

HEALTH_ATT = "Damn Healthy!"
ENERGY_ATT = "Energy Bonus"
SKILL_ATT = "Highly Skilled"

SKILL_COSTS = {"Cyber Punk":
    {"Acrobatics":4, 
    "Animal Training":1, 
    "Architecture":2, 
    "Artisan":2, 
    "Biological Sciences":4, 
    "Boating":2, 
    "Burglary":3,
    "Business Management":2,
    "Computers":5,
    "Controlled Breathing":1,
    "Cooking":1,
    "Cultural Arts":2,
    "Demolitions":3,
    "Disguise":3,
    "Driving":3,
    "Electronics":4,
    "Forgery":3,
    "Gaming":2,
    "Interrogation":3,
    "Intimidation":4,
    "Law":3,
    "Linguistics":2,
    "Mechanics":3,
    "Medical":4,
    "Military Sciences":3,
    "Navigation":2,
    "Performing Arts":2,
    "Physical Sciences":2,
    "Piloting":3,
    "Poisons":2,
    "Police Sciences":3,
    "Riding":1,
    "Seduction":3,
    "Sleight of Hand":2,
    "Social Sciences":2,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":4,
    "Visual Arts":1,
    "Wilderness Survival":1,
    "Wilderness Tracking":1,
    "Writing":2,
    "Archery":4,
    "Gun Combat":5,
    "Heavy Weapons":5,
    "Melee Attack":4,
    "Melee Defense":4,
    "Ranged Defense":5,
    "Thrown Weapons":4,
    "Unarmed Attack":4,
    "Unarmed Attack":4},

"Hotrods and Guns":
    {"Acrobatics":4, 
    "Animal Training":1},

"Martial Arts":
    {"Acrobatics":5, 
    "Animal Training":1},

"Medieval Fantasy":
    {"Acrobatics":3, 
    "Animal Training":2, 
    "Architecture":2, 
    "Artisan":4, 
    "Biological Sciences":2, 
    "Boating":3, 
    "Burglary":4,
    "Business Management":2,
    "Controlled Breathing":2,
    "Cooking":1,
    "Cultural Arts":2,
    "Demolitions":3,
    "Disguise":3,
    "Driving":2,
    "Forgery":2,
    "Gaming":2,
    "Interrogation":3,
    "Intimidation":4,
    "Law":2,
    "Linguistics":3,
    "Mechanics":2,
    "Medical":4,
    "Military Sciences":3,
    "Navigation":2,
    "Performing Arts":2,
    "Physical Sciences":1,
    "Poisons":3,
    "Police Sciences":2,
    "Riding":3,
    "Seduction":3,
    "Sleight of Hand":4,
    "Social Sciences":1,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":3,
    "Visual Arts":2,
    "Wilderness Survival":3,
    "Wilderness Tracking":3,
    "Writing":1,
    "Archery":5,
    "Melee Attack":5,
    "Melee Defense":5,
    "Ranged Defense":4,
    "Thrown Weapons":4,
    "Unarmed Attack":4,
    "Unarmed Attack":4},

"Modern Military":
    {"Acrobatics":2, 
    "Animal Training":1},

"Occult Horror":
    {"Acrobatics":4, 
    "Animal Training":1},

"Space Opera":
    {"Acrobatics":3, 
    "Animal Training":1},

"Teenage Romance":
    {"Acrobatics":3, 
    "Animal Training":1}}
