import random

def _getPony():
    poNames = ["Amethyst","Angel","Applecrunch","Apricot","Aqua","Ballet","Banana","Bay","Be","Beach","Beautiful","Beige","Berry","Bliss","Bloom","Blossom","Blue","Blush","Blushing","Botanical","Breeze","Bright","Bubble","Butter","Buttercup","Butterfly","Cabbage","Camellia","Candlelight","Candy","Canton","Carrot","Cap","Carnation","Champagne","Chateau","Cheerful","Chiffon","Chocolate","Citrus","Cloud","Coast","Cocoa","Cool","Country","Cream","Creamy","Creme","Crocus","Crystal","Daffodil","Daisy","Dance","Dawn","Day","Days","December","Delicate","Delicious","Derry","Dew","Dream","Dune","Dust","Elegance","Elf","Fade","Fading","Fairway","Fall","Falls","Fantasy","Feather","Feather","February","Fine","Fizz","Floe","Floral","Flower","Fog","Frappe","Fresh","Friendship","Frost","Frosted","Frosty","Fruit","Galaxy","Gem","Geyser","Ginger","Glacier","Glade","Glory","Gold","Gown","Graceful","Green","Harvest","Heather","Hint","Honeydew","Hopeful","Hydrangea","Ice","Icy","Iris","Ivory","Ivy","Jade","Jazz","Jewel","Key","Kiwi","Lakeside","Lane","Lavender","Lazy","Lemon","Light","Lilac","Lily","Lime","Little","Lively","Lovelight","Luminary","Majesty","Mantle","Melody","Melon","Melt","Milkshake","Milkyway","Mine","Mint","Minty","Mist","Misty","Mix","Monet","Moon","Moonlit","Moonrise","Morn","Morning","Mountain","Mousse","Murmur","Muted","Nevada","New","Niagara","Night","Opal","Orange","Orchid","Palace","Pale","Panorama","Parfait","Peach","Pear","Pearl","Petal","Pinata","Pineapple","Pink","Poetic","Pond","Pool","Pop","Poppy","Posies","Princess","Provence","Purple","Quartz","Rain","Reef","Refreshing","Resort","Rhapsody","Rich","Roamntic","Rose","Ruffle","Ruffles","Scent","Sea","Seafoam","Sheets","Shell","Shimmer","Silk","Skies","Sky","Skylark","Snowdrop","Soar","Social","Soft","Song","Sorbet","Spirit","Split","Shine","Spark","Spray","Sprite","Squeeze","Star","Starry","Stellar","Straw","Strawberry","Sugar","Summer","Sunday","Sunkiss","Sunlight","Sunrise","Sunshine","Sweet","Taffy","Teal","Tear","Tint","Trail","Tropical","Tuft","Twinkle","Valentine","Vanilla","Violet","Water","Weeping","Whisper","Whispering","White","Wind","Window","Wisteria","Wistful","Yellow","Yogurt","Zephyr","Twilight","Sparkle","Rainbow","Dash","Flutter","Luck","Apple","Heart","Silver","Diamond","Ruby","Sapphire","Emerald"]
    name1 = random.choice(poNames)
    name2 = random.choice(poNames)
    while name2 == name1:
        name2 = random.choice(poNames)
    return name1 + " " + name2
    
def getName(args):
    return _getPony()