ATTRIBUTES = {"Animal Friendship":1,
              "Appearance":1,
              "Art of Distraction":1,
              "Astral Projection":3,
              "Aura of Command":1,
              "Combat Mastery":2,
              "Contamination [Hard]":1,
              "Contamination [Easy]":2,
              "Damn Healthy!":1,
              "Dimensional Portal [Fixed]":2,
              "Dimensional Portal [Mobile]":3,
              "Dimensional Portal [Class]":4,
              "Divine Relationship":1,
              "Dynamic Sorcery":4,
              "Elasticity":1,
              "ECM":1,
              "Energy Bonus":1,
              "Environmental Control [1]":1,
              "Environmental Control [2]":2,
              "Exorcism":1,
              "Extra Arms":1,
              "Extra Attacks":4,
              "Features/Accessories":1,
              "Flight [Airplane]":3,
              "Flight [Hover]":4,
              "Flunkies":1,
              "Focused Damage":1,
              "Force Field [Wall]":2,
              "Force Field [Personal]":3,
              "Force Field [Extendable]":4,
              "Ground Speed":2,
              "Gun Bunny":1,
              "Healing":4,
              "Heavy Armour":4,
              "Heightened Awareness":1,
              "Heightened Senses":1,
              "Highly Skilled":1,
              "Illusion [One Sense]":2,
              "Illusion [Two Senses]":3,
              "Illusion [Three Senses]":4,
              "Illusion [Four Senses]":5,
              "Illusion [All Senses]":6,
              "Insubstantial":4,
              "Invisibility [Normal]":5,
              "Invisibility [Sensors]":3,
              "Invisibility [Both]":7,
              "Item of Power":2,
              "Jumping":1,
              "Kensei":1,
              "Life Support":1,
              "Light Armour":1,
              "Magic":4,
              "Massive Damage":2,
              "Mechanical Genius":2,
              "Meld [Inanimate Class]":2,
              "Meld [Inanimate]":4,
              "Meld [Animate Class]":4,
              "Meld [Animate]":8,
              "Metamorphosis":5,
              "Mind Control [Single Type]":1,
              "Mind Control [Specific]":2,
              "Mind Control [Broad]":3,
              "Mind Control [General]":4,
              "Mind Shield":1,
              "Natural Weapons":1,
              "Organizational Ties [Moderate]":1,
              "Organizational Ties [Significant]":2,
              "Organizational Ties [Great]":3,
              "Own a Big Mecha":4,
              "Personal Gear":1,
              "Place of Power":1,
              "Precognition [Uncontrolled]":1,
              "Precognition [Controllable]":2,
              "Regeneration":4,
              "Reincarnation":3,
              "Sensors":1,
              "Servant [Specific]":1,
              "Servant [Replaceable]":2,
              "Shape Change [Self or Others]":2,
              "Shape Change [Self and Others]":3,
              "Shield":1,
              "Sixth Sense":1,
              "Size Change [Shrink or Grow]":1,
              "Size Change [Shrink and Grow]":2,
              "Space Flight":2,
              "Special Defense":1,
              "Special Movement":1,
              "Speed":1,
              "Spirit Ward":1,
              "Star Flight":2,
              "Stealth":1,
              "Super Strength [Single Limb]":2,
              "Super Strength [Entire Body]":3,
              "Swarm":2,
              "Telekinesis [Focused]":1,
              "Telekinesis [General]":2,
              "Telepathy [Quite Restricted]":1,
              "Telepathy [Somewhat Restricted]":2,
              "Telepathy [Universal]":3,
              "Teleport [Self or Others]":5,
              "Teleport [Self and Others]":10,
              "Transmutation [Very Specific]":1,
              "Transmutation [Class]":2,
              "Transmutation [Universal]":4,
              "Tunnelling":2,
              "Water Speed [Surface]":2,
              "Water Speed [Amphibious/Diving]":3,
              "Weapon/Special Attack":4}
              
DEFECTS = {"Ageism":1,
           "Attack Restriction":1,
           "Awkward":1,
           "Awkward Size":1,
           "Bane":1,
           "Cannot Talk":1,
           "Conditional Ownership":1,
           "Cursed":1,
           "Diminutive":3,
           "Easily Distracted":1,
           "Girl/Guy Magnet":1,
           "Hangar Queen":1,
           "Inept Combat":1,
           "Involuntary Physical Change":1,
           "Magical Restrictions":1,
           "Marked":1,
           "Nemesis":1,
           "Not So Fast":1,
           "Not So Strong":1,
           "Not So Tough":1,
           "One Arm / No Arms":1,
           "One-Way Transformation":1,
           "Owned by a Megacorp":1,
           "Phobia":1,
           "Physically Unappealing":1,
           "Recurring Nightmares":1,
           "Red Tape":1,
           "Restricted Ground Movement":1,
           "Restricted Path":1,
           "Sensory Impairment":1,
           "Significant Other":1,
           "Skeleton in the Closet":1,
           "Special Requirement":1,
           "Unskilled":1,
           "Volatile":1,
           "Vulnerability":1,
           "Wanted":1}

HEALTH_ATT = "Damn Healthy!"
ENERGY_ATT = "Energy Bonus"
SKILL_ATT = "Highly Skilled"
COMBAT_ATT = "Combat Mastery"

HEALTH_DEFECT = "Not So Tough"
SKILL_DEFECT = "Unskilled"
COMBAT_DEFECT = "Inept Combat"

SKILL_COSTS = {"Cyber Punk":
    {"Acrobatics":4, 
    "Animal Training":1, 
    "Architecture":2, 
    "Artisan":2, 
    "Biological Sciences":4, 
    "Boating":2, 
    "Burglary":3,
    "Business Management":2,
    "Computers":5,
    "Controlled Breathing":1,
    "Cooking":1,
    "Cultural Arts":2,
    "Demolitions":3,
    "Disguise":3,
    "Driving":3,
    "Electronics":4,
    "Forgery":3,
    "Gaming":2,
    "Interrogation":3,
    "Intimidation":4,
    "Law":3,
    "Linguistics":2,
    "Mechanics":3,
    "Medical":4,
    "Military Sciences":3,
    "Navigation":2,
    "Performing Arts":2,
    "Physical Sciences":2,
    "Piloting":3,
    "Poisons":2,
    "Police Sciences":3,
    "Riding":1,
    "Seduction":3,
    "Sleight of Hand":2,
    "Social Sciences":2,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":4,
    "Visual Arts":1,
    "Wilderness Survival":1,
    "Wilderness Tracking":1,
    "Writing":2,
    "Archery":4,
    "Gun Combat":5,
    "Heavy Weapons":5,
    "Melee Attack":4,
    "Melee Defense":4,
    "Ranged Defense":5,
    "Thrown Weapons":4,
    "Unarmed Attack":4,
    "Unarmed Defense":4},

"Hotrods and Guns":
    {"Acrobatics":4, 
    "Animal Training":1, 
    "Architecture":1, 
    "Artisan":2, 
    "Biological Sciences":2, 
    "Boating":3, 
    "Burglary":2,
    "Business Management":4,
    "Computers":4,
    "Controlled Breathing":1,
    "Cooking":1,
    "Cultural Arts":2,
    "Demolitions":4,
    "Disguise":3,
    "Driving":6,
    "Electronics":4,
    "Forgery":4,
    "Gaming":2,
    "Interrogation":3,
    "Intimidation":4,
    "Law":2,
    "Linguistics":2,
    "Mechanics":4,
    "Medical":3,
    "Military Sciences":3,
    "Navigation":3,
    "Performing Arts":1,
    "Physical Sciences":2,
    "Piloting":4,
    "Poisons":2,
    "Police Sciences":4,
    "Riding":1,
    "Seduction":2,
    "Sleight of Hand":2,
    "Social Sciences":2,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":4,
    "Visual Arts":1,
    "Wilderness Survival":1,
    "Wilderness Tracking":1,
    "Writing":1,
    "Archery":4,
    "Gun Combat":6,
    "Heavy Weapons":4,
    "Melee Attack":4,
    "Melee Defense":4,
    "Ranged Defense":6,
    "Thrown Weapons":4,
    "Unarmed Attack":4,
    "Unarmed Defense":4},

"Martial Arts":
    {"Acrobatics":5, 
    "Animal Training":1, 
    "Architecture":1, 
    "Artisan":4, 
    "Biological Sciences":1, 
    "Boating":2, 
    "Burglary":2,
    "Business Management":2,
    "Computers":1,
    "Controlled Breathing":3,
    "Cooking":1,
    "Cultural Arts":2,
    "Demolitions":2,
    "Disguise":3,
    "Driving":2,
    "Electronics":2,
    "Forgery":1,
    "Gaming":1,
    "Interrogation":3,
    "Intimidation":4,
    "Law":2,
    "Linguistics":2,
    "Mechanics":2,
    "Medical":4,
    "Military Sciences":2,
    "Navigation":2,
    "Performing Arts":1,
    "Physical Sciences":1,
    "Piloting":2,
    "Poisons":2,
    "Police Sciences":2,
    "Riding":1,
    "Seduction":3,
    "Sleight of Hand":2,
    "Social Sciences":2,
    "Sports":2,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":3,
    "Visual Arts":2,
    "Wilderness Survival":2,
    "Wilderness Tracking":2,
    "Writing":1,
    "Archery":4,
    "Gun Combat":4,
    "Heavy Weapons":4,
    "Melee Attack":6,
    "Melee Defense":6,
    "Ranged Defense":4,
    "Thrown Weapons":5,
    "Unarmed Attack":6,
    "Unarmed Defense":6},

"Medieval Fantasy":
    {"Acrobatics":3, 
    "Animal Training":2, 
    "Architecture":2, 
    "Artisan":4, 
    "Biological Sciences":2, 
    "Boating":3, 
    "Burglary":4,
    "Business Management":2,
    "Controlled Breathing":2,
    "Cooking":1,
    "Cultural Arts":2,
    "Demolitions":3,
    "Disguise":3,
    "Driving":2,
    "Forgery":2,
    "Gaming":2,
    "Interrogation":3,
    "Intimidation":4,
    "Law":2,
    "Linguistics":3,
    "Mechanics":2,
    "Medical":4,
    "Military Sciences":3,
    "Navigation":2,
    "Performing Arts":2,
    "Physical Sciences":1,
    "Poisons":3,
    "Police Sciences":2,
    "Riding":3,
    "Seduction":3,
    "Sleight of Hand":4,
    "Social Sciences":1,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":3,
    "Visual Arts":2,
    "Wilderness Survival":3,
    "Wilderness Tracking":3,
    "Writing":1,
    "Archery":5,
    "Melee Attack":5,
    "Melee Defense":5,
    "Ranged Defense":4,
    "Thrown Weapons":4,
    "Unarmed Attack":4,
    "Unarmed Defense":4},

"Modern Military":
    {"Acrobatics":2, 
    "Animal Training":1, 
    "Architecture":2, 
    "Artisan":2, 
    "Biological Sciences":2, 
    "Boating":2, 
    "Burglary":2,
    "Business Management":2,
    "Computers":4,
    "Controlled Breathing":2,
    "Cooking":1,
    "Cultural Arts":1,
    "Demolitions":3,
    "Disguise":2,
    "Driving":4,
    "Electronics":4,
    "Forgery":2,
    "Gaming":1,
    "Interrogation":3,
    "Intimidation":3,
    "Law":1,
    "Linguistics":2,
    "Mechanics":4,
    "Medical":4,
    "Military Sciences":5,
    "Navigation":3,
    "Performing Arts":1,
    "Physical Sciences":2,
    "Piloting":4,
    "Poisons":2,
    "Police Sciences":1,
    "Riding":1,
    "Seduction":3,
    "Sleight of Hand":2,
    "Social Sciences":2,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":3,
    "Visual Arts":1,
    "Wilderness Survival":3,
    "Wilderness Tracking":3,
    "Writing":1,
    "Archery":3,
    "Gun Combat":5,
    "Heavy Weapons":5,
    "Melee Attack":4,
    "Melee Defense":4,
    "Ranged Defense":5,
    "Thrown Weapons":4,
    "Unarmed Attack":4,
    "Unarmed Defense":4},

"Occult Horror":
    {"Acrobatics":4, 
    "Animal Training":1, 
    "Architecture":1, 
    "Artisan":2, 
    "Biological Sciences":3, 
    "Boating":1, 
    "Burglary":2,
    "Business Management":1,
    "Computers":2,
    "Controlled Breathing":3,
    "Cooking":1,
    "Cultural Arts":1,
    "Demolitions":2,
    "Disguise":2,
    "Driving":2,
    "Electronics":2,
    "Forgery":2,
    "Gaming":1,
    "Interrogation":2,
    "Intimidation":3,
    "Law":1,
    "Linguistics":1,
    "Mechanics":2,
    "Medical":3,
    "Military Sciences":2,
    "Navigation":2,
    "Performing Arts":1,
    "Physical Sciences":2,
    "Piloting":1,
    "Poisons":2,
    "Police Sciences":2,
    "Riding":1,
    "Seduction":2,
    "Sleight of Hand":2,
    "Social Sciences":1,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":3,
    "Visual Arts":1,
    "Wilderness Survival":2,
    "Wilderness Tracking":2,
    "Writing":1,
    "Archery":4,
    "Gun Combat":4,
    "Heavy Weapons":4,
    "Melee Attack":5,
    "Melee Defense":5,
    "Ranged Defense":5,
    "Thrown Weapons":4,
    "Unarmed Attack":5,
    "Unarmed Defense":5},

"Space Opera":
    {"Acrobatics":3, 
    "Animal Training":1, 
    "Architecture":1, 
    "Artisan":1, 
    "Biological Sciences":4, 
    "Boating":1, 
    "Burglary":2,
    "Business Management":2,
    "Computers":4,
    "Controlled Breathing":1,
    "Cooking":1,
    "Cultural Arts":1,
    "Demolitions":2,
    "Disguise":2,
    "Driving":2,
    "Electronics":4,
    "Forgery":2,
    "Gaming":2,
    "Interrogation":2,
    "Intimidation":3,
    "Law":2,
    "Linguistics":2,
    "Mechanics":4,
    "Medical":3,
    "Military Sciences":3,
    "Navigation":3,
    "Performing Arts":1,
    "Physical Sciences":3,
    "Piloting":5,
    "Poisons":1,
    "Police Sciences":3,
    "Riding":1,
    "Seduction":3,
    "Sleight of Hand":2,
    "Social Sciences":2,
    "Sports":1,
    "Stealth":4,
    "Swimming":1,
    "Urban Tracking":3,
    "Visual Arts":1,
    "Wilderness Survival":2,
    "Wilderness Tracking":2,
    "Writing":2,
    "Archery":2,
    "Gun Combat":5,
    "Heavy Weapons":5,
    "Melee Attack":4,
    "Melee Defense":4,
    "Ranged Defense":5,
    "Thrown Weapons":4,
    "Unarmed Attack":4,
    "Unarmed Defense":4},

"Teenage Romance":
    {"Acrobatics":3, 
    "Animal Training":1, 
    "Architecture":1, 
    "Artisan":2, 
    "Biological Sciences":2, 
    "Boating":2, 
    "Burglary":2,
    "Business Management":2,
    "Computers":3,
    "Controlled Breathing":1,
    "Cooking":4,
    "Cultural Arts":4,
    "Demolitions":2,
    "Disguise":2,
    "Driving":4,
    "Electronics":2,
    "Forgery":2,
    "Gaming":4,
    "Interrogation":3,
    "Intimidation":4,
    "Law":2,
    "Linguistics":2,
    "Mechanics":3,
    "Medical":2,
    "Military Sciences":2,
    "Navigation":2,
    "Performing Arts":4,
    "Physical Sciences":2,
    "Piloting":2,
    "Poisons":2,
    "Police Sciences":2,
    "Riding":2,
    "Seduction":4,
    "Sleight of Hand":3,
    "Social Sciences":2,
    "Sports":5,
    "Stealth":3,
    "Swimming":2,
    "Urban Tracking":3,
    "Visual Arts":3,
    "Wilderness Survival":2,
    "Wilderness Tracking":2,
    "Writing":3,
    "Archery":4,
    "Gun Combat":3,
    "Melee Attack":5,
    "Melee Defense":5,
    "Ranged Defense":4,
    "Thrown Weapons":4,
    "Unarmed Attack":5,
    "Unarmed Defense":5}}
